version: '3.5'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - devcloud_internal
    ports:
      - 22181:2181
networks:
  devcloud_internal:
    name: devcloud
  
